name: Buf push

on:
  workflow_call:
    inputs:
      buf-mod-dir:
        required: true
        type: string
        description: Directory where the buf module is located
    secrets:
      BUF_TOKEN:
        required: true
        description: Buf token

jobs:
  buf-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: bufbuild/buf-setup-action@517ee23296d5caf38df31c21945e6a54bbc8a89f # v1.30.0
        with:
          github_token: ${{ github.token }}

      - uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
          input: ${{ inputs.buf-mod-dir }}
