name: Buf push

on:
  workflow_call:
    inputs:
      buf-mod-dir:
        required: true
        type: string
        description: Directory where the buf module is located
    secrets:
      BUF_TOKEN:
        required: true
        description: Buf token

jobs:
  buf-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4

      - uses: bufbuild/buf-setup-action@e7628ee2d941d14dc87d468ed93bdb35c2f7bfea # v1.44.0
        with:
          github_token: ${{ github.token }}

      - uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
          input: ${{ inputs.buf-mod-dir }}
