name: Buf push

on:
  workflow_call:
    inputs:
      buf-mod-dir:
        required: true
        type: string
        description: Directory where the buf module is located
    secrets:
      BUF_TOKEN:
        required: true
        description: Buf token

jobs:
  buf-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: bufbuild/buf-setup-action@058316dbc9b9f2adb1bcfc8b2fce48d74e7292d9 # v1.38.0
        with:
          github_token: ${{ github.token }}

      - uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
          input: ${{ inputs.buf-mod-dir }}
