name: Buf push

on:
  workflow_call:
    inputs:
      buf-mod-dir:
        required: true
        type: string
        description: Directory where the buf module is located
    secrets:
      BUF_TOKEN:
        required: true
        description: Buf token

jobs:
  buf-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - uses: bufbuild/buf-setup-action@f1331ea1d3f74482cbb60ac19f47fa098232b059 # v1.32.0
        with:
          github_token: ${{ github.token }}

      - uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
          input: ${{ inputs.buf-mod-dir }}
